services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    env_file:
      - .env

  worker:
    build: .
    command: rq worker
    depends_on:
      - redis
    volumes:
      - .:/app
    env_file:
      - .env

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: supportdb

volumes:
  postgres_data:
