"""add ticket status

Revision ID: 0fe41da599e1
Revises: ee82513f1280
Create Date: 2024-07-09 23:44:35.202456

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0fe41da599e1'
down_revision: Union[str, None] = 'ee82513f1280'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.execute("ALTER TYPE ticketstatus ADD VALUE 'processing' AFTER 'submitted'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
