"""init

Revision ID: ee82513f1280
Revises: 
Create Date: 2024-07-09 12:27:27.568607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee82513f1280'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('customer_email', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('account_access', 'payment_issue', 'feature_request', 'technical_problem', 'other', name='ticketcategory'), nullable=True),
    sa.Column('priority', sa.Enum('high', 'medium', 'low', name='ticketpriority'), nullable=True),
    sa.Column('status', sa.Enum('submitted', 'processed', name='ticketstatus'), nullable=False),
    sa.Column('initial_response', sa.Text(), nullable=True),
    sa.Column('category_confidence', sa.Float(), nullable=True),
    sa.Column('priority_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tickets')
    # ### end Alembic commands ###
